module.exports = {
  PORT: Number(process.env.PORT),
  PROTOCOL: process.env.PROTOCOL,
  GRAPHHOPPER_SERVICE_NAME: process.env.GRAPHHOPPER_SERVICE_NAME,
  NAMESPACE: process.env.NAMESPACE,
  HOSTNAME: process.env.HOSTNAME,
  PHOTON_SERVICE_NAME: process.env.PHOTON_SERVICE_NAME,
  NOMINATIM_SERVICE_NAME: process.env.NOMINATIM_SERVICE_NAME
};
