module.exports = {
  PORT: Number(process.env.PORT),
  GRAPHHOPPER_SERVICE_NAME: process.env.GRAPHHOPPER_SERVICE_NAME,
  GRAPHHOPPER_PROTOCAL: process.env.GRAPHHOPPER_PROTOCAL,
  NAMESPACE: process.env.NAMESPACE,
  HOSTNAME: process.env.HOSTNAME,
  PHOTON_PROTOCAL: process.env.PHOTON_PROTOCAL,
  PHOTON_SERVICE_NAME: process.env.PHOTON_SERVICE_NAME
};
