---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bikehopper-web-app
  labels:
    app: bikehopper-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bikehopper-web-app
  template:
    metadata:
      labels:
        app: bikehopper-web-app
    spec:
      containers:
      - name: bikehopper-web-app
        image: ghcr.io/bikehopper/bikehopper-web-app:v1.0.0-beta1
        env:
        - name: PORT
          value: '3000'
        - name: PROTOCAL
          value: http
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          value: svc.cluster.local
        - name: GRAPHHOPPER_SERVICE_NAME
          value: graphhopper-svc
        - name: PHOTON_SERVICE_NAME
          value: photon-db-svc
        - name: NOMINATIM_SERVICE_NAME
          value: nominatim-app-svc
        - name: NODE_ENV
          value: production
        ports:
          - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 10
      imagePullSecrets:
      - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: bikehopper-web-app-svc
  labels:
    run: bikehopper-web-app
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
    name: http
  selector:
    app: bikehopper-web-app
